version: "3.3"

services:
  web:
    image: joseluisq/static-web-server:2-alpine
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=80
      - SERVER_DIRECTORY_LISTING=true
      - SERVER_DIRECTORY_LISTING_ORDER=1
      - SERVER_ROOT=./public
      - SERVER_LOG_LEVEL=trace
      - SERVER_LOG_REMOTE_ADDRESS=true
    ports: 
      - "8080:80"
    volumes:
      - ./public:/public

